### ISSUE TITLE
HtmlToReadMe

### ISSUE THREAD

**Issue by Ishasingh04** [Bot-Army/HtmlToReadMe#4]
### All excited to be a part of the Bot-Army and work on HtmlToReadMe project. Looking forward to make my first contribution to open source.
Pls accept my application.

#### Name-Isha Singh
Email-ishasingh412000@gmail.com
#### Skills
* ##### Html
*  ##### CSS3
* ##### Javascript
* ##### Bootstrap
* ##### Basics of React

**Comment by Yashank18** [comment]
Thank you for showing interest. Sent you a link to join. 
Happy Contribution!
